source "https://rubygems.org"

# A rails-like sinatra environment with ActiveRecord, Rake, and ActiveSupport
gem "sinatra", "2.2.3"
gem "sinatra-activerecord", "~> 2.0"
gem "rake"
gem "activesupport"

# We'll use Postgres in all environments
gem "pg"

# Composing JSON views
gem "rabl"

# Pagination for API views
gem "will_paginate", "~> 3.0.6"

# Assists console access
gem "rb-readline"

# Beter API behavior, including passing post body data to params
gem "rack-contrib"

# Remove this if you're not going to use NewRelic
gem "newrelic_rpm"

group :development do
	# Auto-reloading server for development work
	gem "shotgun"
end

group :development, :test do
	# For rspec tests
	gem "rspec"
	gem "pry"
end

group :test do
	# For rspec tests
	gem "factory_girl"
	gem "database_cleaner"
	gem "rack-test"
	gem "rspec-its"
	gem "shoulda-matchers"
	gem "timecop", "~> 0.7.0"
end
